# Hurricane Analysis

## Information of the data:
The data collected on the 34 strongest Atlantic hurricanes are provided in a series of lists. The data includes:

> 1. **name:** names of hurricanes
> 2. **month:** months in which the hurricanes occurred
> 3. **years:** years in which the hurricanes occurred
> 4. **max_sustained_winds:** maximum sustained winds (miles per hour) of the hurricanes
> 5. **areas_affected:** list of different areas affected by each of the hurricanes
> 6. **damages:** cost in USD ($) caused by each of the hurricanes
> 7. **deaths:** total number of deaths caused by each of the hurricanes

The data is organized such that the data at each index, from **0** to **33**, corresponds to the same hurricane.

For example, names[0] yields the “Cuba I” hurricane, which ouccred in months[0] (October) years[0] (1924).

In [4]:
# names of hurricanes
names = ['Cuba I', 'San Felipe II Okeechobee', 'Bahamas', 'Cuba II', 'CubaBrownsville',
'Tampico', 'Labor Day', 'New England', 'Carol', 'Janet', 'Carla', 'Hattie',
'Beulah', 'Camille', 'Edith', 'Anita', 'David', 'Allen', 'Gilbert', 'Hugo',
'Andrew', 'Mitch', 'Isabel', 'Ivan', 'Emily', 'Katrina', 'Rita', 'Wilma',
'Dean', 'Felix', 'Matthew', 'Irma', 'Maria', 'Michael']

# months in which the hurricanes occured
months = ['October', 'September', 'September', 'November', 'August','September', 
'September', 'September', 'September', 'September', 'September', 'October',
'September', 'August', 'September', 'September', 'August', 'August', 
'September', 'September', 'August', 'October', 'September', 'September', 
'July', 'August', 'September', 'October', 'August', 'September', 'October',
'September', 'September', 'October']

# years in which the hurricanes occured
years = [1924, 1928, 1932, 1932, 1933, 1933, 1935, 1938, 1953, 1955, 1961, 1961,
1967, 1969, 1971, 1977, 1979, 1980, 1988, 1989, 1992, 1998, 2003, 2004, 
2005, 2005, 2005, 2005, 2007, 2007, 2016, 2017, 2017, 2018]

# maximum sustained winds (mph = miles per hour) of hurricanes
max_sustained_winds = [165, 160, 160, 175, 160, 160, 185, 160, 160, 175, 175, 160,
160, 175, 160, 175, 175, 190, 185, 160, 175, 180, 165, 165, 160, 175, 180, 185, 175, 175, 165, 180, 175, 160]

# list of different areas affected by each of the hurricanes
areas_affected = [['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'],
['Lesser Antilles', 'The Bahamas', 'United States East Coast', 'Atlantic Canada'], 
['The Bahamas', 'Northeastern United States'],
['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 
['The Bahamas', 'Cuba', 'Florida', 'Texas', 'Tamaulipas'], 
['Jamaica', 'Yucatn Peninsula'], 
['The Bahamas', 'Florida', 'Georgia', 'The Carolinas', 'Virginia'], 
['Southeastern United States', 'Northeastern United States', 'Southwestern Quebec'],
['Bermuda', 'New England', 'Atlantic Canada'], ['Lesser Antilles', 'Central America'],
['Texas', 'Louisiana', 'Midwestern United States'], ['Central America'], 
['The Caribbean', 'Mexico', 'Texas'], ['Cuba', 'United States Gulf Coast'],
['The Caribbean', 'Central America', 'Mexico', 'United States Gulf Coast'],
['Mexico'], ['The Caribbean', 'United States East coast'],
['The Caribbean', 'Yucatn Peninsula', 'Mexico', 'South Texas'], 
['Jamaica', 'Venezuela', 'Central America', 'Hispaniola', 'Mexico'],
['The Caribbean', 'United States East Coast'],
['The Bahamas', 'Florida', 'United States Gulf Coast'],
['Central America', 'Yucatn Peninsula', 'South Florida'],
['Greater Antilles', 'Bahamas', 'Eastern United States', 'Ontario'],
['The Caribbean', 'Venezuela', 'United States Gulf Coast'],
['Windward Islands', 'Jamaica', 'Mexico', 'Texas'],
['Bahamas', 'United States Gulf Coast'], ['Cuba', 'United States Gulf Coast'], 
['Greater Antilles', 'Central America', 'Florida'], ['The Caribbean', 'Central America'], 
['Nicaragua', 'Honduras'], ['Antilles', 'Venezuela', 'Colombia', 'United States East Coast', 'Atlantic Canada'], 
['Cape Verde', 'The Caribbean', 'British Virgin Islands', 'U.S. Virgin Islands', 'Cuba', 'Florida'], 
['Lesser Antilles', 'Virgin Islands', 'Puerto Rico', 'Dominican Republic', 'Turks and Caicos Islands'], 
['Central America', 'United States Gulf Coast (especially Florida Panhandle)']]

# damages (USD($)) of hurricanes
damages = ['Damages not recorded', '100M', 'Damages not recorded', '40M', '27.9M', '5M', 'Damages not recorded', 
'306M', '2M', '65.8M', '326M', '60.3M', '208M', '1.42B', '25.4M', 'Damages not recorded', '1.54B', '1.24B', '7.1B', 
'10B', '26.5B', '6.2B', '5.37B', '23.3B', '1.01B', '125B', '12B', '29.4B', '1.76B', '720M', '15.1B', '64.8B', '91.6B', '25.1B']

# total number of deaths caused by each of the hurricanes
deaths = [90,4000,16,3103,179,184,408,682,5,1023,43,319,688,259,37,11,
2068,269,318,107,65,19325,51,124,17,1836,125,87,45,133,603,138,3057,74]

## Task 1: Updating Damage list
First, let's begin by looking at the **damages** list. The list contains strings representing the total cost in *USD($)* caused by *34* category 5 hurricanes (wind speeds ≥ 157 mph (252 km/h )) in the Atlantic region. For some of the hurricanes, damage data was not recorded (*"Damages not recorded"*), while the rest are written in the format *"Prefix-B/M"*, where *B* stands for *billions (1000000000)* and *M* stands for *millions (1000000)*.

In this first task, a function that returns a new list of updated damages will be written, where the recorded data is converted to **float values** and the missing data is retained as **"Damages not recorded"**.

In [24]:
# Function to update damages list:
def update_damages(damages):
	updated_damages_list = []
	conversion = {"M":1000000, "B" : 1000000000}
	
	for damage in damages:
		if damage[-1] in conversion.keys():
			new_value = float(damage[:-1]) * conversion[damage[-1]]
			updated_damages_list.append(new_value)
		else:
			updated_damages_list.append("Damages not recorded")
	
	return updated_damages_list

In [14]:
# Test the update_damages function
updated_damages = update_damages(damages)
print(updated_damages)

['Damages not recorded', 100000000.0, 'Damages not recorded', 40000000.0, 27900000.0, 5000000.0, 'Damages not recorded', 306000000.0, 2000000.0, 65800000.0, 326000000.0, 60300000.0, 208000000.0, 1420000000.0, 25400000.0, 'Damages not recorded', 1540000000.0, 1240000000.0, 7100000000.0, 10000000000.0, 26500000000.0, 6200000000.0, 5370000000.0, 23300000000.0, 1010000000.0, 125000000000.0, 12000000000.0, 29400000000.0, 1760000000.0, 720000000.0, 15100000000.0, 64800000000.0, 91600000000.0, 25100000000.0]


## Task 2: Organzing Hurricanes by Name (Create Hurricanes by Name Dictionary)
In this task, a function that constructs a dictionary made out of the 7 lists will be written. The keys of the dictionary are the names of the hurricanes, and the values are dictionries themselves containing a key for each piece of data **(Name, Month, Year,Max Sustained Wind, Areas Affected, Damage, Death)** about the hurricane.

For instance, the key *"Cuba I"* would have the value: *{'Name': 'Cuba I', 'Month': 'October', 'Year': 1924, 'Max Sustained Wind': 165, 'Areas Affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 'Damage': 'Damages not recorded', 'Deaths': 90}*.

In [23]:
# Function to construct a dictionary and organize hurricanes by name
def hurricanes_dictionary_by_name(names, months, years, msw, areas_affected, damages, deaths):
	hurricanes_by_name = {}

	for i in range(len(names)):
		hurricanes_by_name[names[i]] = {"Name" : names[i],
						"Month" : months[i],
						"Year" : years[i],
						"Max Sustained Wind" : msw[i],
						"Areas Affected" : areas_affected[i],
						"Damage" : damages[i],
						"Death" : deaths[i]}
	return hurricanes_by_name

In [106]:
# Test hurricanes_dictionary_by_name function
# Create hurricanes dictionary (organized by names)
hurricanes_dictionary = hurricanes_dictionary_by_name(names,months,years, max_sustained_winds, areas_affected, updated_damages, deaths)
print(hurricanes_dictionary['Cuba II'])

{'Name': 'Cuba II', 'Month': 'November', 'Year': 1932, 'Max Sustained Wind': 175, 'Areas Affected': ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 'Damage': 40000000.0, 'Death': 3103}


## Task 3: Organzing Hurricanes by Year (Create Hurricanes by Year Dictionary)

In this task, I will write a function that converts the current **hurricanes_dictionary** (created in task 2) to a new dictionary, where the keys are years and the values are lists containing a dictionary for each hurricane that occurred in that year.

For example, the key *1932* would yield the value: *[{'Name': 'Bahamas', 'Month': 'September', 'Year': 1932, 'Max Sustained Wind': 160, 'Areas Affected': ['The Bahamas', 'Northeastern United States'], 'Damage': 'Damages not recorded', 'Deaths': 16}, {'Name': 'Cuba II', 'Month': 'November', 'Year': 1932, 'Max Sustained Wind': 175, 'Areas Affected': ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 'Damage': 40000000.0, 'Deaths': 3103}]*.


In [30]:
#print(hurricanes_dictionary['Michael']['Year']) # Same format for current_year = hurricanes_dict[hurricane]['Year']
#print(hurricanes_dictionary['Michael']) # current_hurricane = hurricanes_dict[hurricane]

In [54]:
# Function to organize hurricanes by year based on the current hurricanes_dictionary

def hurricanes_dictionary_by_year(hurricanes_dict):
	# Convert hurricanes_dictionary (with hurricane's names as key) to a new dictionary that has year as the key
	hurricanes_by_year = {}

	for hurricane in hurricanes_dict:
		current_year = hurricanes_dict[hurricane]['Year'] # Store the year of the hurricane to current_year
		current_hurricane = hurricanes_dict[hurricane] # Store the data of the hurricane to current_hurricane
		# If the current year is not yet existed in the hurricanes_by_year dict,
		# then create the new key with that year and assign its value with tha data store in current_hurricane
		if current_year not in hurricanes_by_year:
			hurricanes_by_year[current_year] = [current_hurricane]
		# If the year already existed in the hurricanes_by_year dict, then append new value for that year key
		else:
			hurricanes_by_year[current_year].append(current_hurricane)
	
	return hurricanes_by_year

In [55]:
# Test  hurricanes_dictionary_by_year function
# Create hurricanes dictionary (organized by years)
hurricanes_by_year = hurricanes_dictionary_by_year(hurricanes_dictionary)
print(hurricanes_by_year[2017]) # There are 2 hurricanes happened in 2017
print('')
print(hurricanes_by_year[2017][0]) # Access to the first value of the year key 2017

[{'Name': 'Irma', 'Month': 'September', 'Year': 2017, 'Max Sustained Wind': 180, 'Areas Affected': ['Cape Verde', 'The Caribbean', 'British Virgin Islands', 'U.S. Virgin Islands', 'Cuba', 'Florida'], 'Damage': 64800000000.0, 'Death': 138}, {'Name': 'Maria', 'Month': 'September', 'Year': 2017, 'Max Sustained Wind': 175, 'Areas Affected': ['Lesser Antilles', 'Virgin Islands', 'Puerto Rico', 'Dominican Republic', 'Turks and Caicos Islands'], 'Damage': 91600000000.0, 'Death': 3057}]

{'Name': 'Irma', 'Month': 'September', 'Year': 2017, 'Max Sustained Wind': 180, 'Areas Affected': ['Cape Verde', 'The Caribbean', 'British Virgin Islands', 'U.S. Virgin Islands', 'Cuba', 'Florida'], 'Damage': 64800000000.0, 'Death': 138}


## Task 4: Count Affected Areas
It is crucial to know how often each of the areas of the Atlantic are affected by these strong hurricanes with the aims to make preparations for future events.

In this task, a function that counts how often each area is listed as an affected area of a hurricane will be written. The results will be stored in a dictionary where the keys are the affected areas and the values are the counts of how many times the areas were afftected.

In [57]:
# Funtion to create dictionary of areas to store the number of hurricanes involved in based on hurricanes_dictionary (created in task 2)
def areas_affected_count(hurricanes_dict):
	count_affected_areas = {}

	for hurricane in hurricanes_dict:
		for area in hurricanes_dict[hurricane]['Areas Affected']:
			# If the area not yet existed in the count_affected_areas dict, create the key for that area and assign 1 
			if area not in count_affected_areas:
				count_affected_areas[area] = 1
			# If the area already existed, then plus 1 on the top of the current value for that area
			else: 
				count_affected_areas[area] += 1
	
	return count_affected_areas

In [74]:
# Test areas_affected_count function
affected_areas_count_dictionary = areas_affected_count(hurricanes_dictionary)
print(affected_areas_count_dictionary)

{'Central America': 9, 'Mexico': 7, 'Cuba': 6, 'Florida': 6, 'The Bahamas': 7, 'Lesser Antilles': 4, 'United States East Coast': 3, 'Atlantic Canada': 3, 'Northeastern United States': 2, 'Jamaica': 4, 'Cayman Islands': 1, 'Bermuda': 2, 'Texas': 4, 'Tamaulipas': 1, 'Yucatn Peninsula': 3, 'Georgia': 1, 'The Carolinas': 1, 'Virginia': 1, 'Southeastern United States': 1, 'Southwestern Quebec': 1, 'New England': 1, 'Louisiana': 1, 'Midwestern United States': 1, 'The Caribbean': 8, 'United States Gulf Coast': 6, 'United States East coast': 1, 'South Texas': 1, 'Venezuela': 3, 'Hispaniola': 1, 'South Florida': 1, 'Greater Antilles': 2, 'Bahamas': 2, 'Eastern United States': 1, 'Ontario': 1, 'Windward Islands': 1, 'Nicaragua': 1, 'Honduras': 1, 'Antilles': 1, 'Colombia': 1, 'Cape Verde': 1, 'British Virgin Islands': 1, 'U.S. Virgin Islands': 1, 'Virgin Islands': 1, 'Puerto Rico': 1, 'Dominican Republic': 1, 'Turks and Caicos Islands': 1, 'United States Gulf Coast (especially Florida Panhandle)

## Task 5: Find the Most Frequently Affected Area

Now, I already have the dictionary that shows the how often each area of the Atlantic is affected by the hurricanes (task 4). Next, I would like to know which area is affected most frequently. In this task, a funtion that finds the area affected by the most hurricanes, and how often it was hit will be written.

In [80]:
# Funtion to find the most frequently affected area based on the affected_areas_count_dictionary (in task 4)
def find_most_affected_area(affected_areas_count_dict):
	most_affected_area = 'Central America' # Assume Central Amarica is the most affected area
	most_affected_area_count = 0 # Initialize as 0
	
	for area in affected_areas_count_dict:
		if affected_areas_count_dict[area] > most_affected_area_count:
			most_affected_area = area
			most_affected_area_count = affected_areas_count_dict[area]
	return f'The most affected area is {most_affected_area} with {most_affected_area_count} hits.'

In [81]:
most_affected_area = find_most_affected_area(affected_areas_count_dictionary)
print(most_affected_area)

The most affected area is Central America with 9 hits.


## Task 6: Find the Deadliest Hurricane
In this task, I will write a function that finds the hurricane that caused the greatest number of deaths and how many deaths it caused.

In [82]:
# Function to find highest mortality hurricane and the number of deaths

def find_deadliest_hurricane(hurricanes_dict):
	deadliest_hurricane = 'Cuba I' # Assume Cuba I hurricane is the dealiest hurricane
	highest_death = 0

	for hurricane in hurricanes_dict:
		if hurricanes_dict[hurricane]['Death'] > highest_death:
			deadliest_hurricane = hurricane
			highest_death = hurricanes_dict[hurricane]['Death']
	return f'The highest mortality hurricane is {deadliest_hurricane} with {highest_death} deaths.'

In [84]:
# Test the find_deadliest_hurricane function
deadliest_hurricane = find_deadliest_hurricane(hurricanes_dictionary)
print(deadliest_hurricane)

The highest mortality hurricane is Mitch with 19325 deaths.


## Task 7: Rate Hurricanes by Mortality
In this task, I will write a function that rates hurricanes on a mortaility scale according to the following ratings, where the key is the rating and the value is the upper bound of deaths for that rating.

Rate **0**: Hurricanes that caused **no** deaths.

Rate **1**: Hurricanes that caused less than or equal to **100** deaths.

Rate **2**: Hurricanes that caused less than or equal to **500** deaths.

Rate **3**: Hurricanes that caused less than or equal to **1000** deaths.

Rate **4**: Hurricanes that caused less than or equal to **10000** deaths.

Rate **5**: Hurricanes that caused more than **10000** deaths.

In [93]:
# Function to categorize hurricanes in new dictionary with mortality severity as key
def categorize_hurricanes_by_deaths(hurricanes_dict):
	mortality_rating_dict = {0: [], 1: [], 2: [], 3: [], 4: [], 5:[]}
	mortality_scale = {0: 0,
                   1: 100,
                   2: 500,
                   3: 1000,
                   4: 10000}
				   
	for hurricane in hurricanes_dict:
		if hurricanes_dict[hurricane]['Death'] <= mortality_scale[0]:
			mortality_rating_dict[0].append(hurricane)
		elif hurricanes_dict[hurricane]['Death'] <= mortality_scale[1]:
			mortality_rating_dict[1].append(hurricane)
		elif hurricanes_dict[hurricane]['Death'] <= mortality_scale[2]:
			mortality_rating_dict[2].append(hurricane)
		elif hurricanes_dict[hurricane]['Death'] <= mortality_scale[3]:
			mortality_rating_dict[3].append(hurricane)
		elif hurricanes_dict[hurricane]['Death'] <= mortality_scale[4]:
			mortality_rating_dict[4].append(hurricane)
		else:
			mortality_rating_dict[5].append(hurricane)
	
	return mortality_rating_dict

In [87]:
mortality_rating_dictionary = categorize_hurricanes_by_deaths(hurricanes_dictionary)
print(mortality_rating_dictionary)

{0: [], 1: ['Cuba I', 'Bahamas', 'Carol', 'Carla', 'Edith', 'Anita', 'Andrew', 'Isabel', 'Emily', 'Wilma', 'Dean', 'Michael'], 2: ['CubaBrownsville', 'Tampico', 'Labor Day', 'Hattie', 'Camille', 'Allen', 'Gilbert', 'Hugo', 'Ivan', 'Rita', 'Felix', 'Irma'], 3: ['New England', 'Beulah', 'Matthew'], 4: ['San Felipe II Okeechobee', 'Cuba II', 'Janet', 'David', 'Katrina', 'Maria'], 5: ['Mitch']}


## Task 8: Find the Most Damaged Hurricane

A function finding the hurricane that caused the greatest damage, and how costly it was will be written in this task.

In [107]:
# Function to find the greatest damaged hurricane and its cost
def find_greatest_damaged_hurricane(hurricanes_dict):
	greatest_damaged_hurricane = 'Cuba I'
	greatest_cost = float(0)

	for hurricane in hurricanes_dict:
		# To avoid the hurricane with the value of "Damages not recorded"
		if not isinstance(hurricanes_dict[hurricane]['Damage'], str): 
			if hurricanes_dict[hurricane]['Damage'] > greatest_cost:
				greatest_damaged_hurricane = hurricane
				greatest_cost = hurricanes_dict[hurricane]['Damage']
	
	return f'The hurricane causing the greatest damage is {greatest_damaged_hurricane} with the total cost of {greatest_cost} $.'

In [92]:
greatest_damaged_hurricane = find_greatest_damaged_hurricane(hurricanes_dictionary)
print(greatest_damaged_hurricane)

The hurricane causing the greatest damage is Katrina with the total cost of 125000000000.0 $.


## Task 9: Rate Hurricances by Damage Cost
In the last task, I will write a function that rates hurricanes on a damage scale according to the following ratings, where the key is the rating and the value is the upper bound of damage for that rating.

Rate **0**: Hurricanes that caused **no** costs.

Rate **1**: Hurricanes that caused the total cost of less than or equal to **100000000$** (100M).

Rate **2**: Hurricanes that caused the total cost of less than or equal to **1000000000$** (1B).

Rate **3**: Hurricanes that caused the total cost of less than or equal to **10000000000$** (10B).

Rate **4**: Hurricanes that caused the total cost of less than or equal to **50000000000$** (50B).

Rate **5**: Hurricanes that caused the total cost of more than **50000000000$** (50B).

**Damages not recorded**: Hurricanes that has no damages recorded.

In [108]:
# Function to the categorize hurricanes in new dictionary with damage severity as key
def categorize_hurricanes_by_damage(hurricanes_dict):
	damage_rating_dict = {0: [],
					1: [], 
					2: [], 
					3: [], 
					4: [], 
					5: [], 
					"Damages not recorded" :[]}
	damage_scale = {0: 0,
                1: 100000000,
                2: 1000000000,
                3: 10000000000,
                4: 50000000000}
	
	for hurricane in hurricanes_dict:
		# To avoid the hurricane with the value of "Damages not recorded"
		if not isinstance(hurricanes_dict[hurricane]['Damage'], str):
			if hurricanes_dict[hurricane]['Damage'] <= damage_scale[0]:
				damage_rating_dict[0].append(hurricane)
			elif hurricanes_dict[hurricane]['Damage'] <= damage_scale[1]:
				damage_rating_dict[1].append(hurricane)
			elif hurricanes_dict[hurricane]['Damage'] <= damage_scale[2]:
				damage_rating_dict[2].append(hurricane)
			elif hurricanes_dict[hurricane]['Damage'] <= damage_scale[3]:
				damage_rating_dict[3].append(hurricane)
			elif hurricanes_dict[hurricane]['Damage'] <= damage_scale[4]:
				damage_rating_dict[4].append(hurricane)
			else:
				damage_rating_dict[5].append(hurricane)
		else: # Names of hurricane with the value of "Damages not recorded" will be append here
			damage_rating_dict["Damages not recorded"].append(hurricane)

	return damage_rating_dict		

In [111]:
damage_rating_dictionary = categorize_hurricanes_by_damage(hurricanes_dictionary)
print(damage_rating_dictionary)

{0: [], 1: ['San Felipe II Okeechobee', 'Cuba II', 'CubaBrownsville', 'Tampico', 'Carol', 'Janet', 'Hattie', 'Edith'], 2: ['New England', 'Carla', 'Beulah', 'Felix'], 3: ['Camille', 'David', 'Allen', 'Gilbert', 'Hugo', 'Mitch', 'Isabel', 'Emily', 'Dean'], 4: ['Andrew', 'Ivan', 'Rita', 'Wilma', 'Matthew', 'Michael'], 5: ['Katrina', 'Irma', 'Maria'], 'Damages not recorded': ['Cuba I', 'Bahamas', 'Labor Day', 'Anita']}
